/**
 * MOCK WORKSPACE API IMPLEMENTATION
 *
 * ⚠️ THIS IS A PROTOTYPE IMPLEMENTATION ⚠️
 *
 * This file provides a localStorage-backed mock implementation of the workspace API.
 * It is designed to simulate backend behavior for prototyping and development.
 *
 * WHEN CONVERTING TO PRODUCTION:
 * 1. Create a new file: workspaceApi.rest.ts (or workspaceApi.graphql.ts)
 * 2. Implement the IWorkspaceApi interface with real HTTP calls
 * 3. Update the export in workspaceApi.ts to use the new implementation
 * 4. Delete or archive this file
 *
 * MOCK IMPLEMENTATION DETAILS:
 * - Storage: Browser localStorage (key: 'historicalData_workspaces')
 * - ID Generation: Client-side counter (REPLACE with server-generated IDs)
 * - Timestamps: Client-side generation (USE server timestamps in production)
 * - Validation: Minimal (ADD comprehensive validation in production)
 * - Authorization: None (IMPLEMENT user-based auth in production)
 */

import type {
  IWorkspaceApi,
  GetWorkspacesRequest,
  GetWorkspacesResponse,
  GetWorkspaceRequest,
  GetWorkspaceResponse,
  CreateWorkspaceRequest,
  CreateWorkspaceResponse,
  UpdateWorkspaceRequest,
  UpdateWorkspaceResponse,
  DeleteWorkspaceRequest,
  DeleteWorkspaceResponse,
  SetDefaultWorkspaceRequest,
  SetDefaultWorkspaceResponse,
  GetDefaultWorkspaceResponse,
} from './workspaceApi.interface';

// Import as values (not types) since they're instantiated
import {
  WorkspaceApiError,
  WorkspaceErrorCode,
} from './workspaceApi.interface';

import type { Workspace, SerializableWorkspaceData } from '../types';
import { getDefaultWorkspaceId, setDefaultWorkspaceId } from '../utils/userSettings';

// Dynamically import all built-in workspace JSON files
// With eager: true, JSON files are imported directly as the data structure
const builtInWorkspaceModules = import.meta.glob<{
  version: string;
  id: string;
  name: string;
  type: 'builtin';
  data: SerializableWorkspaceData;
}>('../workspace/builtIns/*.json', { eager: true, import: 'default' });

// ============================================================================
// MOCK DATA STORAGE (Replace with database in production)
// ============================================================================

const WORKSPACES_STORAGE_KEY = 'historicalData_workspaces';
const WORKSPACE_COUNTER_KEY = 'historicalData_workspaceCounter';

/**
 * In-memory cache of workspaces
 * PRODUCTION: Remove this, data should come from database
 */
const mockWorkspaces = new Map<string, Workspace>();

/**
 * Client-side ID counter
 * PRODUCTION: IDs should be generated by the backend (UUID, auto-increment, etc.)
 */
let workspaceIdCounter = 0;

/**
 * Simulated network delay (in ms)
 * PRODUCTION: Remove artificial delays
 */
const NETWORK_DELAY = 100;

// ============================================================================
// HELPER FUNCTIONS (Prototype-specific)
// ============================================================================

/**
 * Simulate network delay
 * PRODUCTION: Remove this function
 */
const delay = (ms: number): Promise<void> =>
  new Promise((resolve) => setTimeout(resolve, ms));

/**
 * Save workspaces to localStorage
 * PRODUCTION: Remove this - data persistence happens on the backend
 */
function saveWorkspacesToStorage(): void {
  try {
    const workspacesArray = Array.from(mockWorkspaces.values());
    localStorage.setItem(WORKSPACES_STORAGE_KEY, JSON.stringify(workspacesArray));
    localStorage.setItem(WORKSPACE_COUNTER_KEY, String(workspaceIdCounter));
  } catch (error) {
    console.error('[MOCK] Failed to save workspaces to localStorage:', error);
  }
}

/**
 * Load workspaces from localStorage
 * PRODUCTION: Remove this - data comes from backend API
 */
function loadWorkspacesFromStorage(): void {
  try {
    const stored = localStorage.getItem(WORKSPACES_STORAGE_KEY);
    const counterStored = localStorage.getItem(WORKSPACE_COUNTER_KEY);

    if (stored) {
      const workspacesArray = JSON.parse(stored) as Workspace[];
      mockWorkspaces.clear();
      workspacesArray.forEach((workspace) => {
        mockWorkspaces.set(workspace.id, workspace);
      });
    }

    if (counterStored) {
      workspaceIdCounter = parseInt(counterStored, 10);
    }
  } catch (error) {
    console.error('[MOCK] Failed to load workspaces from localStorage:', error);
  }
}

/**
 * Load built-in workspace from JSON file
 */
function loadBuiltInWorkspace(builtinData: {
  version: string;
  id: string;
  name: string;
  type: 'builtin';
  data: SerializableWorkspaceData;
}): Workspace {
  const now = new Date().toISOString();
  return {
    id: builtinData.id,
    name: builtinData.name,
    type: builtinData.type,
    createdAt: now,
    updatedAt: now,
    data: builtinData.data,
  };
}

/**
 * Initialize built-in workspaces
 * PRODUCTION: Built-in workspaces should be stored in the database
 * and associated with each user account on creation
 */
function initializeBuiltInWorkspaces(): void {
  // First try to load from storage
  loadWorkspacesFromStorage();

  // Get all built-in workspace data from dynamically imported modules
  const builtInWorkspaces = Object.values(builtInWorkspaceModules);

  // Ensure all built-in workspaces are present (add if missing)
  let hasNewBuiltIns = false;
  builtInWorkspaces.forEach((builtinData) => {
    if (!mockWorkspaces.has(builtinData.id)) {
      const workspace = loadBuiltInWorkspace(builtinData);
      mockWorkspaces.set(workspace.id, workspace);
      hasNewBuiltIns = true;
    }
  });

  // If no workspaces existed before, set the first built-in as default
  // Prefer "Power Flows" if it exists, otherwise use the first one
  if (mockWorkspaces.size === builtInWorkspaces.length && !getDefaultWorkspaceId()) {
    const powerFlowsWorkspace = builtInWorkspaces.find(
      (w) => w.id === 'ws-builtin-power-flows'
    );
    const defaultWorkspaceId = powerFlowsWorkspace?.id || builtInWorkspaces[0]?.id;
    if (defaultWorkspaceId) {
      setDefaultWorkspaceId(defaultWorkspaceId);
    }
  }

  // Save if we added new built-ins or if this is the first initialization
  if (hasNewBuiltIns || mockWorkspaces.size === builtInWorkspaces.length) {
    workspaceIdCounter = Math.max(workspaceIdCounter, 1);
    saveWorkspacesToStorage();
  }
}

// Initialize workspaces on module load
// PRODUCTION: Remove auto-initialization
initializeBuiltInWorkspaces();

// ============================================================================
// MOCK API IMPLEMENTATION
// ============================================================================

/**
 * Mock implementation of the Workspace API
 * PRODUCTION: Replace this entire class with real HTTP/GraphQL client
 */
class MockWorkspaceApi implements IWorkspaceApi {
  /**
   * Get all workspaces
   *
   * MOCK BEHAVIOR:
   * - Returns all workspaces from localStorage
   * - No user filtering (returns all workspaces)
   * - Simple array slicing for limit
   *
   * PRODUCTION CHANGES NEEDED:
   * - Add user authentication/authorization
   * - Filter by current user ID
   * - Implement proper pagination (offset/cursor-based)
   * - Add sorting options
   * - Add filtering by type, date range, etc.
   */
  async getWorkspaces(request: GetWorkspacesRequest): Promise<GetWorkspacesResponse> {
    await delay(NETWORK_DELAY);

    let workspaces = Array.from(mockWorkspaces.values());

    // Apply limit if provided
    if (request.limit && request.limit > 0) {
      workspaces = workspaces.slice(0, request.limit);
    }

    // Convert to list items (lightweight metadata)
    const defaultWorkspaceId = getDefaultWorkspaceId();
    const workspaceList = workspaces.map((ws) => ({
      id: ws.id,
      name: ws.name,
      type: ws.type,
      isDefault: ws.id === defaultWorkspaceId,
      createdAt: ws.createdAt,
      updatedAt: ws.updatedAt,
      chartCount: ws.data.charts.length,
    }));

    return {
      workspaces: workspaceList,
    };
  }

  /**
   * Get a specific workspace by ID
   *
   * MOCK BEHAVIOR:
   * - Returns workspace from in-memory Map
   * - No authorization check
   *
   * PRODUCTION CHANGES NEEDED:
   * - Verify user has permission to access this workspace
   * - Return 404 if not found
   * - Return 403 if unauthorized
   * - Consider response caching
   */
  async getWorkspace(request: GetWorkspaceRequest): Promise<GetWorkspaceResponse> {
    await delay(NETWORK_DELAY);

    const workspace = mockWorkspaces.get(request.id);

    if (!workspace) {
      throw new WorkspaceApiError(
        `Workspace not found: ${request.id}`,
        WorkspaceErrorCode.NOT_FOUND
      );
    }

    return {
      workspace,
    };
  }

  /**
   * Create a new workspace
   *
   * MOCK BEHAVIOR:
   * - Generates client-side ID using counter
   * - Sets client-side timestamps
   * - No validation of data structure
   * - No user association
   *
   * PRODUCTION CHANGES NEEDED:
   * - Generate server-side UUID or auto-increment ID
   * - Associate with authenticated user
   * - Validate workspace data structure
   * - Check user quota/limits
   * - Set server-side timestamps
   * - Handle duplicate names (allow or prevent?)
   * - Trigger analytics/logging
   */
  async createWorkspace(request: CreateWorkspaceRequest): Promise<CreateWorkspaceResponse> {
    await delay(150);

    const now = new Date().toISOString();
    const workspace: Workspace = {
      id: `ws-${workspaceIdCounter++}`, // PRODUCTION: Use server-generated ID
      name: request.name,
      type: 'user',
      createdAt: now, // PRODUCTION: Use server timestamp
      updatedAt: now, // PRODUCTION: Use server timestamp
      data: request.data,
    };

    mockWorkspaces.set(workspace.id, workspace);

    // Set as default if requested
    if (request.isDefault) {
      setDefaultWorkspaceId(workspace.id);
    }

    saveWorkspacesToStorage();

    return {
      workspace,
    };
  }

  /**
   * Update an existing workspace
   *
   * MOCK BEHAVIOR:
   * - Direct Map update
   * - Simple built-in protection
   * - No concurrency control
   *
   * PRODUCTION CHANGES NEEDED:
   * - Verify user owns/can edit this workspace
   * - Implement optimistic locking (version number or timestamp)
   * - Handle concurrent updates
   * - Validate data structure if provided
   * - Set server-side updatedAt timestamp
   * - Consider partial updates vs. full replacement
   * - Trigger change notifications/webhooks
   */
  async updateWorkspace(request: UpdateWorkspaceRequest): Promise<UpdateWorkspaceResponse> {
    await delay(150);

    const workspace = mockWorkspaces.get(request.id);

    if (!workspace) {
      throw new WorkspaceApiError(
        `Workspace not found: ${request.id}`,
        WorkspaceErrorCode.NOT_FOUND
      );
    }

    // Prevent any modifications to built-in workspaces
    if (workspace.type === 'builtin') {
      throw new WorkspaceApiError(
        'Cannot modify built-in workspaces',
        WorkspaceErrorCode.VALIDATION_ERROR
      );
    }

    const now = new Date().toISOString();
    const updatedWorkspace: Workspace = {
      ...workspace,
      name: request.name ?? workspace.name,
      data: request.data ?? workspace.data,
      updatedAt: now, // PRODUCTION: Use server timestamp
    };

    mockWorkspaces.set(request.id, updatedWorkspace);
    saveWorkspacesToStorage();

    return {
      workspace: updatedWorkspace,
    };
  }

  /**
   * Delete a workspace
   *
   * MOCK BEHAVIOR:
   * - Simple Map deletion
   * - Basic built-in protection
   *
   * PRODUCTION CHANGES NEEDED:
   * - Verify user owns/can delete this workspace
   * - Prevent deletion of built-in workspaces
   * - Consider soft delete for recovery
   * - Handle cascade deletes if applicable
   * - Trigger cleanup of related resources
   * - Log deletion for audit trail
   */
  async deleteWorkspace(request: DeleteWorkspaceRequest): Promise<DeleteWorkspaceResponse> {
    await delay(100);

    const workspace = mockWorkspaces.get(request.id);

    if (!workspace) {
      throw new WorkspaceApiError(
        `Workspace not found: ${request.id}`,
        WorkspaceErrorCode.NOT_FOUND
      );
    }

    // Prevent deletion of built-in workspaces
    if (workspace.type === 'builtin') {
      throw new WorkspaceApiError(
        'Cannot delete built-in workspaces',
        WorkspaceErrorCode.VALIDATION_ERROR
      );
    }

    mockWorkspaces.delete(request.id);
    saveWorkspacesToStorage();

    return {
      success: true,
    };
  }

  /**
   * Set a workspace as the default
   *
   * MOCK BEHAVIOR:
   * - Updates user settings with default workspace ID
   *
   * PRODUCTION CHANGES NEEDED:
   * - Use atomic database transaction
   * - Ensure only one default per user
   * - Handle concurrent requests
   * - Verify user owns the workspace
   */
  async setDefaultWorkspace(
    request: SetDefaultWorkspaceRequest
  ): Promise<SetDefaultWorkspaceResponse> {
    await delay(100);

    const workspace = mockWorkspaces.get(request.id);

    if (!workspace) {
      throw new WorkspaceApiError(
        `Workspace not found: ${request.id}`,
        WorkspaceErrorCode.NOT_FOUND
      );
    }

    // Set the workspace as default in user settings
    setDefaultWorkspaceId(request.id);

    return {
      success: true,
    };
  }

  /**
   * Get the default workspace
   *
   * MOCK BEHAVIOR:
   * - Looks up default workspace ID from user settings
   * - No user filtering
   *
   * PRODUCTION CHANGES NEEDED:
   * - Query database with user ID filter
   * - Cache result client-side
   * - Handle case where no default is set (return first workspace?)
   */
  async getDefaultWorkspace(): Promise<GetDefaultWorkspaceResponse> {
    await delay(100);

    const defaultWorkspaceId = getDefaultWorkspaceId();
    const defaultWorkspace = defaultWorkspaceId
      ? mockWorkspaces.get(defaultWorkspaceId)
      : undefined;

    return {
      workspace: defaultWorkspace ?? null,
    };
  }
}

// ============================================================================
// EXPORT
// ============================================================================

/**
 * Export singleton instance of the mock API
 * PRODUCTION: Replace with real API client instance
 */
export const mockWorkspaceApi = new MockWorkspaceApi();

/**
 * Testing utilities
 * PRODUCTION: Remove these or move to test files
 */
export const __testing__ = {
  clearWorkspaces: () => {
    mockWorkspaces.clear();
    workspaceIdCounter = 0;
    initializeBuiltInWorkspaces();
  },
  getWorkspacesMap: () => mockWorkspaces,
  resetCounter: () => {
    workspaceIdCounter = 0;
  },
};
